mutation CreateUser($id: String!, $username: String!) @auth(expr: "auth.uid == id") {
  user_insert(data: {id: $id, username: $username, highScore: 0})
}

mutation UpdateHighScore($id: String!, $score: Int!) @auth(expr: "auth.uid == id") {
  user_update(id: $id, data: {highScore: $score})
}

query GetLeaderboard($limit: Int!) @auth(level: PUBLIC, insecureReason: "Leaderboard scores are public information") {
  users(limit: $limit, orderBy: [{highScore: DESC}]) {
    username
    highScore
  }
}

query GetUsername($id: String!) @auth(level: PUBLIC, insecureReason: "Usernames are public profile info") {
  user(id: $id) {
    username
  }
}
