type User @table {
  googleId: String!
  displayName: String!
  createdAt: Timestamp!
  photoUrl: String
}

type GameSession @table {
  user: User!
  score: Int!
  createdAt: Timestamp!
}

type HighScore @table {
  user: User!
  score: Int!
  createdAt: Timestamp!
  updatedAt: Timestamp!
}
